# Generated by Django 3.0.11 on 2021-02-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
                'ordering': ('naziv',),
            },
        ),
        migrations.CreateModel(
            name='Ploca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('slika', models.ImageField(blank=True, upload_to='ploce/%Y/%m/%d')),
                ('pesme', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('na_stanju', models.BooleanField(default=True)),
                ('kreirana', models.DateTimeField(auto_now_add=True)),
                ('azurirana', models.DateTimeField(auto_now=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ploce', to='ProdavnicaPloca.Kategorija')),
            ],
            options={
                'verbose_name_plural': 'ploce',
                'ordering': ('naziv',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
