# Generated by Django 3.0.11 on 2021-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProdavnicaPloca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ploca',
            options={'ordering': ('album',), 'verbose_name_plural': 'ploce'},
        ),
        migrations.RenameField(
            model_name='ploca',
            old_name='naziv',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='ploca',
            name='album',
            field=models.CharField(db_index=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='ploca',
            name='cena',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
